-- Payment through the venue's system and the guest's word after the visit.
-- The bill learns when the visit ends and when the guest was sent the payment link; the review is one row per bill.

ALTER TABLE guest_bills ADD COLUMN IF NOT EXISTS visit_ends_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE guest_bills ADD COLUMN IF NOT EXISTS payment_link_sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE guest_bills ADD COLUMN IF NOT EXISTS paid_notified_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_guest_bills_visit_ends
    ON guest_bills(visit_ends_at);

-- No free text from the guest here: words go through the feedback scenario, this holds the stars and the thumb.
CREATE TABLE IF NOT EXISTS visit_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT NOT NULL REFERENCES guest_bills(id),
    chat_id BIGINT NOT NULL,
    prompted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    stars INT,
    thumb VARCHAR(8), -- UP or DOWN; the application's enum keeps it so
    tip_requested_at TIMESTAMP WITH TIME ZONE,
    rated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_visit_reviews_bill UNIQUE (bill_id),
    CONSTRAINT chk_visit_reviews_stars CHECK (stars IS NULL OR (stars >= 1 AND stars <= 5))
);

CREATE INDEX IF NOT EXISTS idx_visit_reviews_chat
    ON visit_reviews(chat_id, created_at DESC);
