-- MAX messenger channel, phase 1 (docs/architecture/MAX_ADAPTER_PLAN.md).
-- The FSM state, drafts, timeline and Kafka events are keyed by a numeric chatId, and the gateway treats a negative
-- chatId as a group chat. A MAX chat therefore gets an internal chat id from its own range, never its raw MAX id:
-- 8e12 + n for a dialog and -(8e12 + n) for a group chat. Telegram ids stay far below this range and the web chat
-- uses 9e12..9.9e12, so the three channels cannot share an FSM key. The table only maps ids; nothing is deleted.

CREATE SEQUENCE IF NOT EXISTS messenger_internal_chat_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS messenger_chat_bindings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(32) NOT NULL,
    external_chat_id BIGINT NOT NULL,
    external_user_id BIGINT,
    chat_type VARCHAR(32) NOT NULL,
    internal_chat_id BIGINT NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    username VARCHAR(255),
    locale VARCHAR(32),
    contact_phone VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_messenger_chat_bindings_external UNIQUE (channel, external_chat_id),
    CONSTRAINT uq_messenger_chat_bindings_internal UNIQUE (internal_chat_id)
);

CREATE INDEX IF NOT EXISTS idx_messenger_chat_bindings_user
    ON messenger_chat_bindings(channel, external_user_id);
