-- Guest bills mirror what the venue's own system (Saby Presto) holds; Butler never takes the money.
-- No guest names or phones here: a bill points at the chat and the reservation that already carry them.

CREATE TABLE IF NOT EXISTS guest_bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    kind VARCHAR(40) NOT NULL,
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    table_reservation_id BIGINT,
    external_provider VARCHAR(40),
    external_order_id VARCHAR(160),
    status VARCHAR(40) NOT NULL DEFAULT 'ESTIMATED',
    pay_state VARCHAR(40) NOT NULL DEFAULT 'NOT_REPORTED',
    estimate_minor BIGINT,
    venue_amount_minor BIGINT,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    price_source VARCHAR(160),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_guest_bills_estimate CHECK (estimate_minor IS NULL OR estimate_minor > 0),
    CONSTRAINT chk_guest_bills_venue_amount CHECK (venue_amount_minor IS NULL OR venue_amount_minor >= 0),
    CONSTRAINT uq_guest_bills_kind_reservation UNIQUE (kind, table_reservation_id),
    CONSTRAINT uq_guest_bills_external_order UNIQUE (external_provider, external_order_id)
);

CREATE INDEX IF NOT EXISTS idx_guest_bills_chat_created
    ON guest_bills(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_guest_bills_status_created
    ON guest_bills(status, created_at DESC);

CREATE TABLE IF NOT EXISTS guest_bill_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT NOT NULL REFERENCES guest_bills(id),
    line_no INT NOT NULL,
    item_code VARCHAR(80),
    title VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    unit_price_minor BIGINT,
    included BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_guest_bill_lines_quantity CHECK (quantity > 0),
    CONSTRAINT uq_guest_bill_lines_line_no UNIQUE (bill_id, line_no)
);

-- Append-only: the application only inserts and reads these rows.
CREATE TABLE IF NOT EXISTS bill_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT NOT NULL REFERENCES guest_bills(id),
    type VARCHAR(40) NOT NULL,
    ok BOOLEAN NOT NULL DEFAULT TRUE,
    actor VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    error_code VARCHAR(80),
    details VARCHAR(500),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bill_operations_bill
    ON bill_operations(bill_id, id);

CREATE INDEX IF NOT EXISTS idx_bill_operations_type_time
    ON bill_operations(type, occurred_at DESC);

-- One row per HTTP call to Saby: method, path without ids or query, status, duration. No bodies, tokens or guest data.
CREATE TABLE IF NOT EXISTS saby_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    http_method VARCHAR(10) NOT NULL,
    operation VARCHAR(200) NOT NULL,
    http_status INT NOT NULL DEFAULT 0,
    outcome VARCHAR(20) NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_saby_call_log_time
    ON saby_call_log(occurred_at DESC);
