-- Telegram voice replies: the guest's hands-free toggle (/voice on|off) and the full answers behind "Подробнее".

ALTER TABLE telegram_profiles ADD COLUMN IF NOT EXISTS voice_replies_hands_free BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE telegram_profiles ADD COLUMN IF NOT EXISTS voice_replies_updated_at TIMESTAMP WITH TIME ZONE;

-- One row per summarised answer; the inline button carries only the id, the text stays here. Rows are pruned by age.
CREATE TABLE IF NOT EXISTS telegram_reply_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    full_text TEXT NOT NULL,
    html BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telegram_reply_details_created
    ON telegram_reply_details(created_at);
