package museon_online.astor_butler.domain.billing;

public enum BillOperationType {
    ESTIMATE_CREATED,
    ISSUED_TO_VENUE,
    VENUE_SUBMIT_FAILED,
    PAY_STATE_CHANGED,
    PAYMENT_LINK_ISSUED,
    PAYMENT_LINK_FAILED,
    PAID_NOTIFIED,
    REVIEW_PROMPTED,
    REVIEW_RECEIVED,
    TIP_REQUESTED,
    VENUE_AMOUNT_REPORTED,
    AMOUNT_MISMATCH,
    CANCELLED
}
