import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const file = name => readFileSync(new URL(`../${name}`, import.meta.url), 'utf8');
const realm = JSON.parse(file('astor-realm.json'));
const ui = realm.clients.find(c => c.clientId === 'astor-staff-ui');
test('production realm contains no identities, credentials or speculative mobile callback', () => {
  assert.equal(realm.realm, 'astor');
  assert.equal(realm.sslRequired, 'all');
  assert.equal(realm.registrationAllowed, false);
  assert.equal(realm.bruteForceProtected, true);
  assert.equal(realm.accessTokenLifespan, 300);
  assert.deepEqual(realm.users, []);
  assert.deepEqual(realm.clients.map(c => c.clientId).sort(), ['astor-api', 'astor-staff-ui']);
  assert.ok(realm.clients.every(c => !c.secret && !c.credentials));
});
test('staff UI requires PKCE with an exact HTTPS callback and no password/implicit flow', () => {
  assert.equal(ui.publicClient, true);
  assert.equal(ui.standardFlowEnabled, true);
  assert.equal(ui.directAccessGrantsEnabled, false);
  assert.equal(ui.implicitFlowEnabled, false);
  assert.equal(ui.serviceAccountsEnabled, false);
  assert.equal(ui.attributes['pkce.code.challenge.method'], 'S256');
  assert.deepEqual(ui.redirectUris, ['https://c3ag.ru/astor/staff/']);
  assert.deepEqual(ui.webOrigins, ['https://c3ag.ru']);
  assert.equal(ui.attributes['post.logout.redirect.uris'], ui.redirectUris[0]);
});
test('audience and tenant are access-token-only and tenant profile is admin-only', () => {
  const audience = ui.protocolMappers.find(m => m.protocolMapper === 'oidc-audience-mapper');
  assert.equal(audience.config['included.client.audience'], 'astor-api');
  const mapper = ui.protocolMappers.find(m => m.name === 'astor-tenant');
  assert.equal(mapper.config.multivalued, 'false');
  assert.equal(mapper.config['access.token.claim'], 'true');
  assert.equal(mapper.config['id.token.claim'], 'false');
  const component = realm.components['org.keycloak.userprofile.UserProfileProvider'][0];
  const profile = JSON.parse(component.config['kc.user.profile.config'][0]);
  assert.notEqual(profile.unmanagedAttributePolicy, 'ENABLED');
  const tenant = profile.attributes.find(a => a.name === 'tenant');
  assert.deepEqual(tenant.permissions, {view: ['admin'], edit: ['admin']});
  assert.equal(tenant.multivalued, false);
  assert.ok(tenant.validations.pattern.pattern);
});
test('dedicated container/database use file secrets, bounded resources and private networks', () => {
  const compose = file('compose.yaml');
  assert.ok(compose.includes('name: astor-identity'));
  assert.ok(compose.includes('POSTGRES_DB: astor_identity'));
  assert.ok(compose.includes('127.0.0.1:18880:8080'));
  assert.ok(compose.includes('ASTOR_IDENTITY_POSTGRES_IMAGE:?'));
  assert.ok(compose.includes('ASTOR_IDENTITY_KEYCLOAK_BASE:?'));
  assert.ok(compose.includes('POSTGRES_PASSWORD_FILE:'));
  assert.ok(compose.includes('internal: true'));
  assert.ok(compose.includes('cap_drop: [ALL]'));
  assert.ok(!compose.includes('vedal') && !compose.includes('astor_postgres_test'));
  assert.ok(!compose.includes('KC_DB_PASSWORD:') && !compose.includes('KC_BOOTSTRAP_ADMIN_PASSWORD:'));
  assert.ok(!compose.includes('9000:') && !compose.includes('0.0.0.0:18880'));
});
test('gateway exposes only Astor realm/assets and overwrites forwarding identity', () => {
  const nginx = file('nginx-locations.conf');
  assert.match(nginx, /location \^~ \/astor-auth\/realms\/astor\//);
  assert.match(nginx, /location \^~ \/astor-auth\/resources\//);
  assert.match(nginx, /location \^~ \/astor-auth\/ \{ return 404; \}/);
  assert.ok(!nginx.includes('include ') && !nginx.includes('realms/master/ {'));
  assert.ok(nginx.includes('proxy_set_header X-Forwarded-For $remote_addr;'));
  assert.ok(nginx.includes('proxy_set_header X-Forwarded-Proto https;'));
  assert.ok(nginx.includes('access_log off;') && nginx.includes('proxy_cache off;'));
});
test('entrypoint preserves signals; optimized image build has no runtime credentials', () => {
  assert.ok(file('entrypoint.sh').includes('exec /opt/keycloak/bin/kc.sh "$@"'));
  assert.ok(file('Dockerfile').includes('RUN /opt/keycloak/bin/kc.sh build'));
  assert.ok(file('Dockerfile').includes('"--optimized"'));
  assert.ok(file('Dockerfile').includes('KC_HTTP_RELATIVE_PATH=/astor-auth'));
  assert.ok(file('Dockerfile').includes('KC_HTTP_MANAGEMENT_RELATIVE_PATH=/'));
  assert.ok(!file('Dockerfile').includes('start-dev'));
  assert.ok(!file('Dockerfile').includes('KC_DB_PASSWORD='));
});
