platform :ios, '15.0'
source 'https://cdn.cocoapods.org/'
project 'AstorGlassesProbe.xcodeproj'
target 'AstorGlassesProbe' do
  sdk_path = ENV.fetch('ASTOR_AIBUDS_SDK_PATH') { abort 'Set ASTOR_AIBUDS_SDK_PATH to the licensed AIBuds-SDK-iOS checkout' }
  pod 'AIBudsSDK/ABMate', :path => sdk_path
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
